Fix Sample Server Code To Actually Run
The prior code didn't run/work - with these changes there's now a "hello world" that actually runs the server.

Original Errors:
# command-line-arguments
./server.go:17:9: cannot use &Session{} (type *Session) as type smtp.Session in return argument:
	*Session does not implement smtp.Session (wrong type for Mail method)
		have Mail(string, *smtp.MailOptions) error
		want Mail(string, smtp.MailOptions) error
./server.go:58:21: cannot use be (type *Backend) as type smtp.Backend in argument to smtp.NewServer:
	*Backend does not implement smtp.Backend (missing AnonymousLogin method)